/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.farmgui.GUI;
import com.mycompany.farmgui.Clases.CabeceraFactura;
import com.mycompany.farmgui.Clases.Contabilidadd;
import com.mycompany.farmgui.Clases.DetalleFactura;
import com.mycompany.farmgui.Clases.Fecha;
import com.mycompany.farmgui.Clases.GeneradorID;
import com.mycompany.farmgui.Clases.General;
import com.mycompany.farmgui.Clases.Haber;
import com.mycompany.farmgui.Clases.Persona;
import com.mycompany.farmgui.Clases.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sebas
 */
public class Facturacion extends javax.swing.JFrame {

    
    DefaultTableModel dtm1=new DefaultTableModel();
    DefaultTableModel dtm2=new DefaultTableModel();
    
    private General g1;
    ArrayList<CabeceraFactura> cf1 = g1.getCabeceraFacturas();
    ArrayList<Persona> clientes = g1.getListaClientes();
    ArrayList<DetalleFactura> carrito= new ArrayList();
    ArrayList<Producto> stock = g1.getStock();
    ArrayList<DetalleFactura> detalles=g1.getDetalleFacturas();
    GeneradorID id = new GeneradorID();
    Contabilidadd c1=g1.getConta();
    public Facturacion( ) {
        initComponents();
         g1 = new General();
       
        String tx[]={"Codigo","Cliente","Fecha"};
        dtm1.setColumnIdentifiers(tx);
        jTable.setModel(dtm1);
        
        String txt[]={"Producto","Cantidad","Pre. Uni","Pre. Tot"};
        dtm2.setColumnIdentifiers(txt);
        jTable1.setModel(dtm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visualizarFacturaBT = new javax.swing.JButton();
        nuevaFacturaBT = new javax.swing.JButton();
        regresarBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        visualizarFacturaJP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        mostrarFacturaBT = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nuevaFacturaJP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cedulaClienteTF = new javax.swing.JTextField();
        clienteEncontradoTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombretTF = new javax.swing.JTextField();
        direccionTF = new javax.swing.JTextField();
        anadirClienteBT = new javax.swing.JButton();
        generarFactura = new javax.swing.JButton();
        verificarBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        prodTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cantidadTF = new javax.swing.JTextField();
        facturaJP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayFacturacionTP = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        visualizarFacturaBT.setBackground(new java.awt.Color(51, 102, 0));
        visualizarFacturaBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        visualizarFacturaBT.setForeground(new java.awt.Color(255, 255, 255));
        visualizarFacturaBT.setText("Visualizar Factura");
        visualizarFacturaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarFacturaBTActionPerformed(evt);
            }
        });

        nuevaFacturaBT.setBackground(new java.awt.Color(51, 102, 0));
        nuevaFacturaBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        nuevaFacturaBT.setForeground(new java.awt.Color(255, 255, 255));
        nuevaFacturaBT.setText("Nueva Factura");
        nuevaFacturaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaFacturaBTActionPerformed(evt);
            }
        });

        regresarBT.setBackground(new java.awt.Color(51, 102, 0));
        regresarBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        regresarBT.setForeground(new java.awt.Color(255, 255, 255));
        regresarBT.setText("Regresar al Menú");
        regresarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevaFacturaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualizarFacturaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(visualizarFacturaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(nuevaFacturaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(regresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 70));

        jPanel3.setLayout(new java.awt.CardLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        mostrarFacturaBT.setText("Mostrar Factura");
        mostrarFacturaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarFacturaBTActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout visualizarFacturaJPLayout = new javax.swing.GroupLayout(visualizarFacturaJP);
        visualizarFacturaJP.setLayout(visualizarFacturaJPLayout);
        visualizarFacturaJPLayout.setHorizontalGroup(
            visualizarFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarFacturaJPLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(visualizarFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visualizarFacturaJPLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(visualizarFacturaJPLayout.createSequentialGroup()
                        .addComponent(mostrarFacturaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(166, 166, 166))))
        );
        visualizarFacturaJPLayout.setVerticalGroup(
            visualizarFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarFacturaJPLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(visualizarFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarFacturaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel3.add(visualizarFacturaJP, "card2");

        jLabel1.setText("Ingrese la Cédula del Cliente");

        cedulaClienteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaClienteTFActionPerformed(evt);
            }
        });

        clienteEncontradoTF.setEnabled(false);

        jLabel2.setText("Dirección");

        jLabel3.setText("Nombre");

        anadirClienteBT.setText("Añadir Cliente");
        anadirClienteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirClienteBTActionPerformed(evt);
            }
        });

        generarFactura.setText("Generar Factura");
        generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarFacturaActionPerformed(evt);
            }
        });

        verificarBT.setText("Verificar Cliente");
        verificarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarBTActionPerformed(evt);
            }
        });

        jLabel4.setText("Productos");

        prodTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodTFActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar:");

        jLabel6.setText("Carrito");

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel7.setText("Cantidad:");

        javax.swing.GroupLayout nuevaFacturaJPLayout = new javax.swing.GroupLayout(nuevaFacturaJP);
        nuevaFacturaJP.setLayout(nuevaFacturaJPLayout);
        nuevaFacturaJPLayout.setHorizontalGroup(
            nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                        .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                .addComponent(cedulaClienteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(verificarBT)
                                .addGap(51, 51, 51)
                                .addComponent(clienteEncontradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombretTF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135)
                                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                        .addComponent(direccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(anadirClienteBT))))
                            .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(82, 82, 82)
                                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(prodTF, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButton1)))))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generarFactura)
                        .addGap(58, 58, 58))))
        );
        nuevaFacturaJPLayout.setVerticalGroup(
            nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaClienteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteEncontradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificarBT))
                .addGap(18, 18, 18)
                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombretTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anadirClienteBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(generarFactura)
                        .addGap(130, 130, 130))
                    .addGroup(nuevaFacturaJPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nuevaFacturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))))
        );

        jPanel3.add(nuevaFacturaJP, "card3");

        displayFacturacionTP.setEditable(false);
        jScrollPane3.setViewportView(displayFacturacionTP);

        javax.swing.GroupLayout facturaJPLayout = new javax.swing.GroupLayout(facturaJP);
        facturaJP.setLayout(facturaJPLayout);
        facturaJPLayout.setHorizontalGroup(
            facturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturaJPLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        facturaJPLayout.setVerticalGroup(
            facturaJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturaJPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.add(facturaJP, "card4");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 780, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarFacturaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFacturaBTActionPerformed
            visualizarFacturaJP.setVisible(true);
            nuevaFacturaJP.setVisible(false);
            ArrayList<CabeceraFactura> cf1 = g1.getCabeceraFacturas();
             dtm1.setRowCount(0);
      System.out.println("Número de elementos en cf1: " + cf1.size());
        for (CabeceraFactura cabecera : cf1) {
             System.out.println("Añadiendo fila para factura: " + cabecera.getCodigoFactura());
        dtm1.addRow(new Object[]{cabecera.getCodigoFactura(), cabecera.getCliente().getCedula(), cabecera.getFecha()});
        ((DefaultTableModel) jTable.getModel()).fireTableDataChanged();
    }
            
    }//GEN-LAST:event_visualizarFacturaBTActionPerformed

    private void nuevaFacturaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaFacturaBTActionPerformed
        visualizarFacturaJP.setVisible(false);
        nuevaFacturaJP.setVisible(true);
                
                
    }//GEN-LAST:event_nuevaFacturaBTActionPerformed

    private void regresarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBTActionPerformed
        Menu m1= new Menu();
        m1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_regresarBTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
      dtm1.setRowCount(0);
      System.out.println("Número de elementos en cf1: " + cf1.size());
        for (CabeceraFactura cabecera : cf1) {
             System.out.println("Añadiendo fila para factura: " + cabecera.getCodigoFactura());
        dtm1.addRow(new Object[]{cabecera.getCodigoFactura(), cabecera.getCliente().getCedula(), cabecera.getFecha()});
        ((DefaultTableModel) jTable.getModel()).fireTableDataChanged();
    }
        ((DefaultTableModel) jTable.getModel()).fireTableDataChanged();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablePropertyChange
   
        jTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                int filaSeleccionada = jTable.getSelectedRow();
                
                // Verifica si se ha seleccionado una fila
                if (filaSeleccionada != -1) {
                    // Accede a los datos de la fila seleccionada en el ArrayList
                    CabeceraFactura cfProv = cf1.get(filaSeleccionada);
                    cfProv.getCodigoFactura();
                    
                    
                }
            }
        });
    }//GEN-LAST:event_jTablePropertyChange
    
    
    private void mostrarFacturaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarFacturaBTActionPerformed
          mostrarFacturaBT.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Obtener la fila seleccionada
        int filaSeleccionada = jTable.getSelectedRow();

        // Verificar si se seleccionó una fila
        if (filaSeleccionada != -1) {
            // Obtener el objeto Persona asociado a la fila seleccionada
            CabeceraFactura personaSeleccionada = cf1.get(filaSeleccionada);
            displayFacturacionTP.setText(personaSeleccionada.mostrarFactura());     
            visualizarFacturaJP.setVisible(false);
            nuevaFacturaJP.setVisible(false);
            facturaJP.setVisible(true);
        }
    }
});
           
    }//GEN-LAST:event_mostrarFacturaBTActionPerformed

    private void cedulaClienteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaClienteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaClienteTFActionPerformed

    private void anadirClienteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirClienteBTActionPerformed
      String nombre,cedula,direccion;
   
      nombre=nombretTF.getText();
      cedula=cedulaClienteTF.getText();
      direccion=direccionTF.getText();
      
      
      if(!nombre.isEmpty()){
          if (!direccion.isEmpty()) {
      if (cedula.matches("^17\\d{8}$")) {
          if (g1.buscarCliente(clientes, cedula)==null) {
               g1.añadirCliente(cedula,nombre,direccion);
                JOptionPane.showMessageDialog(null, "Cliente ingresado con éxito.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
          }else {
        JOptionPane.showMessageDialog(this, "Ya existe un cliente con cédula "+cedula+".",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
          
        } else {
        JOptionPane.showMessageDialog(this, "Ingrese un número de cédula válido.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
      
      }else {
        JOptionPane.showMessageDialog(this, "Dirección no ingresada.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
      }
      else {
        JOptionPane.showMessageDialog(this, "Nombre no ingresado.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
     
    }//GEN-LAST:event_anadirClienteBTActionPerformed

    private void verificarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarBTActionPerformed
        String ced;
       ced = cedulaClienteTF.getText();
       
       Persona clienteAux=g1.buscarCliente(clientes, ced);
       if(clienteAux!=null){
       clienteEncontradoTF.setText("Cliente Existente");
       }else{
       clienteEncontradoTF.setText("Cliente no Existente");
       }
       
       
       
       if (ced.matches("^17\\d{8}$")) {
    // Cédula válida
    clienteAux = g1.buscarCliente(clientes, ced);
    if (clienteAux != null) {
        clienteEncontradoTF.setText("Cliente Existente");
    } else {
        clienteEncontradoTF.setText("Cliente no Existente");
    }
} else {
    // Cédula no válida
   JOptionPane.showMessageDialog(this, "Ingrese una cédula valida.",
                "Error", JOptionPane.ERROR_MESSAGE);
}
       
       
       
       
       
    }//GEN-LAST:event_verificarBTActionPerformed

    private void prodTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String prod;
       int cant;
       prod = prodTF.getText();
       try {
    cant = Integer.parseInt(cantidadTF.getText());
       Producto productoAux=g1.buscarProducto(stock, prod);
  
       if(productoAux!=null){
             if ( productoAux.verificarStock(cant)) {
                  productoAux.incrementarStock(-cant);
               carrito.add(new DetalleFactura(new Producto(productoAux.getNombre(),productoAux.getPrecio(),cant),cant));
              
                 System.out.println("a:"+stock.get(0));
               dtm2.setRowCount(0);
               System.out.println("Número de elementos en cf1: " + cf1.size());
               for (DetalleFactura carr : carrito) {
               System.out.println("Añadiendo fila para factura: " + carr.getProducto().getNombre());
               dtm2.addRow(new Object[]{carr.getProducto().getNombre(), carr.getCantidadProducto(), productoAux.getPrecio(),carr.getValorProductos()});
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
    }                                    

               
           }else{JOptionPane.showMessageDialog(this, "Stock Insuficiente, stock disponible: "+productoAux.getStock(), "Error", JOptionPane.ERROR_MESSAGE);
       }
           
       }else{
       JOptionPane.showMessageDialog(this, "Producto no Encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
       }
       } catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese un número entero).", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFacturaActionPerformed
        String cedula=cedulaClienteTF.getText();
        int i=0;
        if(g1.buscarCliente(clientes, cedula)!=null){
            if(!carrito.isEmpty()){
            Persona cliente=g1.buscarCliente(clientes, cedula);
            String a=id.generarID();
        
             cf1.add(new CabeceraFactura(a,cliente,new Fecha(0,0,0).getFechaActual()));
        
        for(i=0;i<carrito.size();i++){
            cf1.get(cf1.size()-1).añadirDetalle(carrito.get(i));
           
        }
        cf1.get(cf1.size()-1).calcularSubtotal();
        cf1.get(cf1.size()-1).calcularTotal();
        c1.agregarHaber(new Haber(new Fecha(0,0,0).getFechaActual(),"Facturación ID: "+cf1.get(cf1.size()-1).getCodigoFactura(),cf1.get(cf1.size()-1).getTotal()));
      displayFacturacionTP.setText( g1.buscarCabeceraPorNumero(cf1, a).mostrarFactura());
            visualizarFacturaJP.setVisible(false);
            nuevaFacturaJP.setVisible(false);
            facturaJP.setVisible(true);
        
            }
            else {
    // Cédula no válida
   JOptionPane.showMessageDialog(this, "Añada al menos un producto al carrito.",
                "Error", JOptionPane.ERROR_MESSAGE);
}
    }else {
    // Cédula no válida
   JOptionPane.showMessageDialog(this, "Verifique la existencia del cliente.",
                "Error", JOptionPane.ERROR_MESSAGE);
}
       carrito.clear();
        
    }//GEN-LAST:event_generarFacturaActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(() -> {
            new Facturacion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirClienteBT;
    private javax.swing.JTextField cantidadTF;
    private javax.swing.JTextField cedulaClienteTF;
    private javax.swing.JTextField clienteEncontradoTF;
    private javax.swing.JTextField direccionTF;
    private javax.swing.JTextPane displayFacturacionTP;
    private javax.swing.JPanel facturaJP;
    private javax.swing.JButton generarFactura;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostrarFacturaBT;
    private javax.swing.JTextField nombretTF;
    private javax.swing.JButton nuevaFacturaBT;
    private javax.swing.JPanel nuevaFacturaJP;
    private javax.swing.JTextField prodTF;
    private javax.swing.JButton regresarBT;
    private javax.swing.JButton verificarBT;
    private javax.swing.JButton visualizarFacturaBT;
    private javax.swing.JPanel visualizarFacturaJP;
    // End of variables declaration//GEN-END:variables
}
