/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.farmgui.GUI;
import com.mycompany.farmgui.Clases.CabeceraFactura;
import com.mycompany.farmgui.Clases.Fecha;
import com.mycompany.farmgui.Clases.GeneradorID;
import com.mycompany.farmgui.Clases.General;
import static com.mycompany.farmgui.Clases.General.id;
import com.mycompany.farmgui.Clases.Pedido;
import com.mycompany.farmgui.Clases.Producto;
import com.mycompany.farmgui.Clases.Proveedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sebas
 */
public class Proveedores extends javax.swing.JFrame {

    private General g1;
    GeneradorID gid=new GeneradorID();
    DefaultTableModel dtm6=new DefaultTableModel();
    DefaultTableModel dtm7=new DefaultTableModel();
    DefaultTableModel dtm8=new DefaultTableModel();
    DefaultTableModel dtm9=new DefaultTableModel();
    DefaultTableModel dtm10=new DefaultTableModel();
    ArrayList<Proveedor> proveedores = g1.getProveedores();
    ArrayList<Producto> prodAux =new ArrayList();
    ArrayList<Producto> carrito =new ArrayList();
    ArrayList<Producto> stock = g1.getStock();
    
 
    Proveedor proveedorSelec=new Proveedor("","","");
    Pedido p=new Pedido(carrito,new Fecha(0,0,0).getFechaActual(),"");
    String empresaSeleccionada = "";
    String estadoSeleccionado = "";
    String id="";
         
    
    
    
    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        
        initComponents();
        g1=new General();
        String tx[]={"Proveedor","RUC","Telefono"};
        dtm6.setColumnIdentifiers(tx);
        jTable1.setModel(dtm6);
        
        String txt[]={"Proveedores"};
        dtm7.setColumnIdentifiers(txt);
        jTable2.setModel(dtm7);
        
        String txtx[]={"Nombre","Precio"};
        dtm8.setColumnIdentifiers(txtx);
        jTable4.setModel(dtm8);
        
        String txtxt[]={"Producto","Cantidad","Precio Unitario","Precio Total"};
        dtm9.setColumnIdentifiers(txtxt);
        jTable6.setModel(dtm9);
        
        String txtxtx[]={"Proveedor","ID pedido","Estado","Fecha del Pedido"};
        dtm10.setColumnIdentifiers(txtxtx);
        jTable3.setModel(dtm10);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        proveedoresBT = new javax.swing.JButton();
        hacerPedidoBT = new javax.swing.JButton();
        estadoPedidoBT = new javax.swing.JButton();
        regresarBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        proveedoresJP = new javax.swing.JPanel();
        ingresarHaber12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ingresarHaber13 = new javax.swing.JLabel();
        ingresarHaber14 = new javax.swing.JLabel();
        nombreEmpresaTF = new javax.swing.JTextField();
        ingresarHaber15 = new javax.swing.JLabel();
        rucTF = new javax.swing.JTextField();
        ingresarHaber16 = new javax.swing.JLabel();
        telefTF = new javax.swing.JTextField();
        proveedoresBT1 = new javax.swing.JButton();
        eliminarListaProveedoresBT = new javax.swing.JButton();
        ingresarHaber18 = new javax.swing.JLabel();
        ingresarHaber19 = new javax.swing.JLabel();
        nomProdTF = new javax.swing.JTextField();
        ingresarHaber21 = new javax.swing.JLabel();
        precioTF = new javax.swing.JTextField();
        añadirProductoProvBT = new javax.swing.JButton();
        actualizarBT = new javax.swing.JButton();
        ingresarHaber25 = new javax.swing.JLabel();
        precioVTF = new javax.swing.JTextField();
        hacerPedidoJP = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        seleccionarBT = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        ingresarHaber20 = new javax.swing.JLabel();
        ingresarHaber22 = new javax.swing.JLabel();
        ingresarHaber24 = new javax.swing.JLabel();
        cantidadTF = new javax.swing.JTextField();
        ingresarHaber26 = new javax.swing.JLabel();
        cancelarBT = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        estadoPedidoJP = new javax.swing.JPanel();
        ingresarHaber17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pedidosEntregadosBT = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        proveedoresBT.setBackground(new java.awt.Color(181, 181, 11));
        proveedoresBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        proveedoresBT.setForeground(new java.awt.Color(255, 255, 255));
        proveedoresBT.setText("Proveedores");
        proveedoresBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresBTActionPerformed(evt);
            }
        });

        hacerPedidoBT.setBackground(new java.awt.Color(181, 181, 11));
        hacerPedidoBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        hacerPedidoBT.setForeground(new java.awt.Color(255, 255, 255));
        hacerPedidoBT.setText("Hacer Pedido");
        hacerPedidoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerPedidoBTActionPerformed(evt);
            }
        });

        estadoPedidoBT.setBackground(new java.awt.Color(181, 181, 11));
        estadoPedidoBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        estadoPedidoBT.setForeground(new java.awt.Color(255, 255, 255));
        estadoPedidoBT.setText("Estado del Pedido");
        estadoPedidoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoPedidoBTActionPerformed(evt);
            }
        });

        regresarBT.setBackground(new java.awt.Color(181, 181, 11));
        regresarBT.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        regresarBT.setForeground(new java.awt.Color(255, 255, 255));
        regresarBT.setText("Regresar al Menú");
        regresarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoPedidoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hacerPedidoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedoresBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(proveedoresBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(hacerPedidoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(estadoPedidoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(regresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 790, 70));

        jPanel3.setLayout(new java.awt.CardLayout());

        ingresarHaber12.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber12.setText("Lista de Proveedores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ingresarHaber13.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber13.setText("Añadir Producto");

        ingresarHaber14.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ingresarHaber14.setText("Nombre Producto");

        nombreEmpresaTF.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        nombreEmpresaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEmpresaTFActionPerformed(evt);
            }
        });

        ingresarHaber15.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ingresarHaber15.setText("RUC");

        rucTF.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        rucTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rucTFActionPerformed(evt);
            }
        });

        ingresarHaber16.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ingresarHaber16.setText("Telefono");

        telefTF.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        telefTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefTFActionPerformed(evt);
            }
        });

        proveedoresBT1.setBackground(new java.awt.Color(204, 204, 204));
        proveedoresBT1.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        proveedoresBT1.setText("Añadir");
        proveedoresBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresBT1ActionPerformed(evt);
            }
        });

        eliminarListaProveedoresBT.setText("Eliminar");
        eliminarListaProveedoresBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarListaProveedoresBTActionPerformed(evt);
            }
        });

        ingresarHaber18.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber18.setText("Añadir Proveedor");

        ingresarHaber19.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ingresarHaber19.setText("Nombre Empresa");

        nomProdTF.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        nomProdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomProdTFActionPerformed(evt);
            }
        });

        ingresarHaber21.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ingresarHaber21.setText("Precio Proveedor");

        precioTF.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        precioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTFActionPerformed(evt);
            }
        });

        añadirProductoProvBT.setBackground(new java.awt.Color(204, 204, 204));
        añadirProductoProvBT.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        añadirProductoProvBT.setText("Añadir");
        añadirProductoProvBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirProductoProvBTActionPerformed(evt);
            }
        });

        actualizarBT.setText("Actualizar");
        actualizarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBTActionPerformed(evt);
            }
        });

        ingresarHaber25.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ingresarHaber25.setText("Precio de Venta");

        precioVTF.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        precioVTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioVTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout proveedoresJPLayout = new javax.swing.GroupLayout(proveedoresJP);
        proveedoresJP.setLayout(proveedoresJPLayout);
        proveedoresJPLayout.setHorizontalGroup(
            proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedoresJPLayout.createSequentialGroup()
                .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proveedoresJPLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ingresarHaber12, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(proveedoresJPLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(proveedoresJPLayout.createSequentialGroup()
                                    .addComponent(ingresarHaber18, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(actualizarBT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eliminarListaProveedoresBT)
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, proveedoresJPLayout.createSequentialGroup()
                                    .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombreEmpresaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ingresarHaber19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(proveedoresJPLayout.createSequentialGroup()
                                            .addComponent(ingresarHaber15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60)
                                            .addComponent(ingresarHaber16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(proveedoresJPLayout.createSequentialGroup()
                                            .addComponent(rucTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(telefTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(proveedoresBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, proveedoresJPLayout.createSequentialGroup()
                                    .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ingresarHaber13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, proveedoresJPLayout.createSequentialGroup()
                                            .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nomProdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ingresarHaber14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(proveedoresJPLayout.createSequentialGroup()
                                                    .addComponent(ingresarHaber21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ingresarHaber25, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(proveedoresJPLayout.createSequentialGroup()
                                                    .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(precioVTF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(54, 54, 54)
                                                    .addComponent(añadirProductoProvBT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        proveedoresJPLayout.setVerticalGroup(
            proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedoresJPLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ingresarHaber12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proveedoresJPLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminarListaProveedoresBT)
                            .addComponent(actualizarBT)))
                    .addGroup(proveedoresJPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ingresarHaber18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarHaber15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarHaber16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarHaber19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEmpresaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rucTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedoresBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresarHaber13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proveedoresJPLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(añadirProductoProvBT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(proveedoresJPLayout.createSequentialGroup()
                        .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(proveedoresJPLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(ingresarHaber14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proveedoresJPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ingresarHaber21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingresarHaber25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(proveedoresJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomProdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioVTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.add(proveedoresJP, "card2");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        seleccionarBT.setText("Seleccionar");
        seleccionarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarBTActionPerformed(evt);
            }
        });

        jButton3.setText("Añadir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jButton4.setText("Hacer Pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ingresarHaber20.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber20.setText("Productos del Proveedor Elegido");

        ingresarHaber22.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber22.setText("Lista de Proveedores");

        ingresarHaber24.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber24.setText("Carrito");

        ingresarHaber26.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber26.setText("Cantidad");

        cancelarBT.setText("Cancelar Pedido");
        cancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar del carrito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hacerPedidoJPLayout = new javax.swing.GroupLayout(hacerPedidoJP);
        hacerPedidoJP.setLayout(hacerPedidoJPLayout);
        hacerPedidoJPLayout.setHorizontalGroup(
            hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                        .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarBT)
                            .addComponent(ingresarHaber24, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(ingresarHaber20, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hacerPedidoJPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hacerPedidoJPLayout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hacerPedidoJPLayout.createSequentialGroup()
                                        .addComponent(ingresarHaber26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jButton3)
                                        .addGap(29, 29, 29))))))
                    .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hacerPedidoJPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(50, 50, 50))
                            .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(cancelarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 41, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hacerPedidoJPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(ingresarHaber22, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(554, Short.MAX_VALUE)))
        );
        hacerPedidoJPLayout.setVerticalGroup(
            hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ingresarHaber20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seleccionarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresarHaber24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(ingresarHaber26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarBT)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(79, 79, 79))))
            .addGroup(hacerPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hacerPedidoJPLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(ingresarHaber22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
        );

        jPanel3.add(hacerPedidoJP, "card3");

        ingresarHaber17.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresarHaber17.setText("ESTADO DEL PEDIDO");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("Marcar Como Entregado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pedidosEntregadosBT.setText("Pedidos Anteriores");
        pedidosEntregadosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosEntregadosBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout estadoPedidoJPLayout = new javax.swing.GroupLayout(estadoPedidoJP);
        estadoPedidoJP.setLayout(estadoPedidoJPLayout);
        estadoPedidoJPLayout.setHorizontalGroup(
            estadoPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadoPedidoJPLayout.createSequentialGroup()
                .addGroup(estadoPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estadoPedidoJPLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ingresarHaber17, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(estadoPedidoJPLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(estadoPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(estadoPedidoJPLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                                .addComponent(pedidosEntregadosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(85, 85, 85))
        );
        estadoPedidoJPLayout.setVerticalGroup(
            estadoPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadoPedidoJPLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ingresarHaber17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(estadoPedidoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(pedidosEntregadosBT))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jPanel3.add(estadoPedidoJP, "card4");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proveedoresBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresBTActionPerformed
         hacerPedidoJP.setVisible(false);
        estadoPedidoJP.setVisible(false);
        proveedoresJP.setVisible(true);

         dtm6.setRowCount(0);
        for (Proveedor prov : proveedores) {
             
        dtm6.addRow(new Object[]{prov.getEmpresa(), prov.getRUC(), prov.getTelefono()});
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
    }
    }//GEN-LAST:event_proveedoresBTActionPerformed

    private void hacerPedidoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerPedidoBTActionPerformed
        hacerPedidoJP.setVisible(true);
        estadoPedidoJP.setVisible(false);
        proveedoresJP.setVisible(false);
        
        
        dtm7.setRowCount(0);
      
        for (Proveedor prov : proveedores) {
        dtm7.addRow(new Object[]{prov.getEmpresa()});
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
    }
        
        
        
    }//GEN-LAST:event_hacerPedidoBTActionPerformed

    private void estadoPedidoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoPedidoBTActionPerformed
        hacerPedidoJP.setVisible(false);
        estadoPedidoJP.setVisible(true);
        proveedoresJP.setVisible(false);
        int i =0;
        dtm10.setRowCount(0);
        for (Proveedor prov : proveedores) {
            System.out.println("l 0");
               System.out.println("l 1");
               
             for(i=0;i < prov.getPedidos().size();i++){
                 if (prov.getPedidos().get(i).getEstado().equals("Pendiente")) {
                    
                 System.out.println(""+prov.getEmpresa()+ prov.getPedidos().get(i).getEstado()+prov.getPedidos().get(i).getFecha());
                dtm10.addRow(new Object[]{prov.getEmpresa(),prov.getPedidos().get(i).getID() ,prov.getPedidos().get(i).getEstado(),prov.getPedidos().get(i).getFecha() });
             }
                 }
        ((DefaultTableModel) jTable3.getModel()).fireTableDataChanged();
    
        }

    }//GEN-LAST:event_estadoPedidoBTActionPerformed

    
    private void regresarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBTActionPerformed
        Menu m1= new Menu();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarBTActionPerformed

    private void nombreEmpresaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEmpresaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEmpresaTFActionPerformed

    private void rucTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rucTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rucTFActionPerformed

    private void telefTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefTFActionPerformed

    private void proveedoresBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresBT1ActionPerformed
       String nombre,RUC, telefono;
       nombre=nombreEmpresaTF.getText();
       RUC=rucTF.getText();
       telefono=telefTF.getText();
       Proveedor pAux=g1.buscarProveedorRUC(proveedores, RUC);
       boolean rUcB=false;
       boolean telefB=telefono.matches("^09\\d{8}$");
      
       
       
       if(g1.buscarProveedorRUC(proveedores, RUC)==null){
       if(!nombre.isEmpty()){
       if (RUC.matches("^\\d{13}$")) {
          if(telefB){
              g1.añadirProveedor(nombre, RUC, telefono);
          }else {
        JOptionPane.showMessageDialog(this, "Ingrese un número de teléfono valido (10 dígitos)",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
      } else {
        JOptionPane.showMessageDialog(this, "RUC no valido, ingrese su RUC y 001 al final. \nEjemplo: 0296537341001",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
      }
       else{
           JOptionPane.showMessageDialog(this, "Ingrese un nombre para la Empresa.",
                "Error", JOptionPane.ERROR_MESSAGE);
              }}
   else{
        JOptionPane.showMessageDialog(this, "RUC ya registrado.",
                "Error", JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_proveedoresBT1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void nomProdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomProdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomProdTFActionPerformed

    private void precioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTFActionPerformed

    private void añadirProductoProvBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirProductoProvBTActionPerformed
        String nombreProd;
        double precio,precioVenta;
        nombreProd=nomProdTF.getText();
        
        if (!nombreProd.trim().isEmpty()) {
            System.out.println("vacio");
                try {
        precio = Double.parseDouble(precioTF.getText());
        

    try {
        precioVenta = Double.parseDouble(precioVTF.getText());
        int filaSeleccionada = jTable1.getSelectedRow();
         
        if (filaSeleccionada != -1) {
            // Obtener el objeto Persona asociado a la fila seleccionada
            proveedorSelec = proveedores.get(filaSeleccionada);
            if(proveedorSelec.buscarProducto(nombreProd)==null){
            proveedorSelec.agregarProducto(new Producto(nombreProd,precio,0));
                if (g1.buscarProducto(stock, nombreProd)==null) {
                    g1.añadirProductoStock(nombreProd, precioVenta);
            
                }
            JOptionPane.showMessageDialog(null, "Producto ingresado con éxito para "+proveedorSelec.getEmpresa(), "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
            
            }else{
                JOptionPane.showMessageDialog(this, "Producto ya existente en el proveedor "+proveedorSelec.getEmpresa()+".",
                "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else{
             JOptionPane.showMessageDialog(this, "Seleccione el proveedor al cuál se le agregará el producto",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        }  catch (NumberFormatException e) {
        // Manejar la excepción si no se puede convertir a double
        JOptionPane.showMessageDialog(this, "Ingrese un precio de venta válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }}catch (NumberFormatException e) {
        // Manejar la excepción si no se puede convertir a double
        JOptionPane.showMessageDialog(this, "Ingrese un precio de proveedor válido.",
                "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }else{
          JOptionPane.showMessageDialog(this, "Ingrese un nombre para el producto.",
                "Error", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_añadirProductoProvBTActionPerformed

    private void seleccionarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarBTActionPerformed
         int filaSeleccionada = jTable2.getSelectedRow();
         
        if (filaSeleccionada != -1) {
        prodAux=(ArrayList<Producto>) proveedores.get(filaSeleccionada).getProductosProveedor();
        proveedorSelec=proveedores.get(filaSeleccionada);
            System.out.println("seleccionado: " + proveedorSelec.getEmpresa());
        dtm7.setRowCount(0);
        
 dtm8.setRowCount(0);
        for (Producto prods : prodAux) {
             
        dtm8.addRow(new Object[]{prods.getNombre(),prods.getPrecio()});
        ((DefaultTableModel) jTable4.getModel()).fireTableDataChanged();
    }
          
        }
       seleccionarBT.setVisible(false);
        
        
        
        
        
    }//GEN-LAST:event_seleccionarBTActionPerformed

    private void actualizarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBTActionPerformed
         dtm6.setRowCount(0);
        for (Proveedor prov : proveedores) {
             
        dtm6.addRow(new Object[]{prov.getEmpresa(), prov.getRUC(), prov.getTelefono()});
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
    }
                
                
                
    }//GEN-LAST:event_actualizarBTActionPerformed

    private void precioVTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioVTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioVTFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filaSeleccionada = jTable4.getSelectedRow();
        
        if(!proveedorSelec.getEmpresa().isEmpty()){
        if (filaSeleccionada != -1) {
         
         String prod;
         double precioAux;
         prod=prodAux.get(filaSeleccionada).getNombre();
         int cant;
         try{
         cant = Integer.parseInt(cantidadTF.getText());
         precioAux=prodAux.get(filaSeleccionada).getPrecio();
             if (cant>0) {

         carrito.add(new Producto(prod,precioAux,cant));
         }else{
             JOptionPane.showMessageDialog(this, "Ingrese un número positivo.",
                "Error", JOptionPane.ERROR_MESSAGE); 
             }
         }catch (NumberFormatException e) {
        // Manejar la excepción si no se puede convertir a double
        JOptionPane.showMessageDialog(this, "Ingrese una cantidad valida.",
                "Error", JOptionPane.ERROR_MESSAGE); 
    }
         
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione un producto.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un proveedor para mostrar sus productos.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
      
        
         dtm9.setRowCount(0);
        for (Producto carr : carrito) {
             
        dtm9.addRow(new Object[]{carr.getNombre(), carr.getStock(), carr.getPrecio(),carr.getPrecio()*carr.getStock()});
        ((DefaultTableModel) jTable6.getModel()).fireTableDataChanged();
    }
         dtm9.addRow(new Object[]{"","","Total:",p.getPrecio()});
        ((DefaultTableModel) jTable6.getModel()).fireTableDataChanged();
       
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTActionPerformed
        
          int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de cancelar la compra?\nEsta operación será irreversible",
            "Confirmación", JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.YES_OPTION) {
          carrito.clear();
          
            JOptionPane.showMessageDialog(null, "Producto eliminado con Éxito.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
            
            
             dtm7.setRowCount(0);
             for (Proveedor prov : proveedores) {
        dtm7.addRow(new Object[]{prov.getEmpresa()});
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
         
        dtm8.setRowCount(0);
        dtm9.setRowCount(0);
          seleccionarBT.setVisible(true);
        
        
    }
        
            
            
        }else {
     JOptionPane.showMessageDialog(null, "Operación cancelada.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
    }
       
      
    }//GEN-LAST:event_cancelarBTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

       
        
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío, ingrese productos para poder continuar",
                "Error", JOptionPane.ERROR_MESSAGE);
        }else{
         ArrayList<Producto> copiaCarrito = new ArrayList<>(carrito);
            
            
        p=(new Pedido(copiaCarrito, new Fecha(0,0,0).getFechaActual(),gid.generarID()));


        if (g1.buscarProveedor(proveedores, proveedorSelec.getEmpresa())!=null) {
            g1.buscarProveedorRUC(proveedores, proveedorSelec.getRUC()).añadirPedido(p);
            
            JOptionPane.showMessageDialog(null, "Pedido con ID " + p.getID()+" realizado con éxito a "+
                    g1.buscarProveedorRUC(proveedores, proveedorSelec.getRUC()).getEmpresa(), "Confirmación", JOptionPane.INFORMATION_MESSAGE);

              dtm8.setRowCount(0);
              dtm9.setRowCount(0);
              dtm7.setRowCount(0);
      
        for (Proveedor prov : proveedores) {
        dtm7.addRow(new Object[]{prov.getEmpresa()});
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
        
        
    }
              
        }
        else{
            System.out.println("salio nulo");
            System.out.println(""+proveedorSelec.getEmpresa());
        }
        
      
        System.out.println(""+proveedorSelec.getPedidos().get(0).getEstado());
 
        seleccionarBT.setVisible(true);
        carrito.clear();
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      for (Proveedor prove : proveedores) {
                if(g1.buscarPedido(prove.getPedidos(), id)!=null){
                     System.out.println("prov"+g1.buscarProveedor(proveedores, empresaSeleccionada).getEmpresa());
                g1.buscarPedido(prove.getPedidos(), id).actualizarEstado(true);
               
               // g1.incrementarStok( g1.buscarProveedor(proveedores, empresaSeleccionada).getPedido(id).getProductos());
               for(Producto ppp: g1.buscarProveedor(proveedores, empresaSeleccionada).getPedido(id).getProductos()){
                  if( g1.buscarStock(ppp.getNombre())!=null){
                      g1.buscarStock(ppp.getNombre()).incrementarStock(ppp.getStock());
                      }else{
                              stock.add(ppp);
                              }
                  }
                }
                
                }
   
      dtm10.setRowCount(0);
        for (Proveedor prov : proveedores) {   
             for(int i=0;i < prov.getPedidos().size();i++){
                 if (prov.getPedidos().get(i).getEstado().equals("Pendiente")) {
                    
                 System.out.println(""+prov.getEmpresa()+ prov.getPedidos().get(i).getEstado()+prov.getPedidos().get(i).getFecha());
                dtm10.addRow(new Object[]{prov.getEmpresa(),prov.getPedidos().get(i).getID() ,prov.getPedidos().get(i).getEstado(),prov.getPedidos().get(i).getFecha() });
             }
                 }
        ((DefaultTableModel) jTable3.getModel()).fireTableDataChanged();
    
        }
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
       
     int selectedRow = jTable3.getSelectedRow();

        // Verificar que se haya seleccionado alguna fila
        if (selectedRow != -1) {
            // Obtener información de la fila seleccionada
            empresaSeleccionada = (String) jTable3.getValueAt(selectedRow, 0);
            estadoSeleccionado = (String) jTable3.getValueAt(selectedRow, 2);
            id=(String) jTable3.getValueAt(selectedRow,1);
            System.out.println(""+empresaSeleccionada);
            
            
        }
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void pedidosEntregadosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosEntregadosBTActionPerformed
 int i=0;
 dtm10.setRowCount(0);
        for (Proveedor prov : proveedores) {
            System.out.println("l 0");
               System.out.println("l 1");
               
             for(i=0;i < prov.getPedidos().size();i++){
                 if (prov.getPedidos().get(i).getEstado().equals("Entregado")) {
                    
                 System.out.println(""+prov.getEmpresa()+ prov.getPedidos().get(i).getEstado()+prov.getPedidos().get(i).getFecha());
                dtm10.addRow(new Object[]{prov.getEmpresa(),prov.getPedidos().get(i).getID() ,prov.getPedidos().get(i).getEstado(),prov.getPedidos().get(i).getFecha() });
             }
                 }
        ((DefaultTableModel) jTable3.getModel()).fireTableDataChanged();
    
        }        
        
        
        
        
        
        
    }//GEN-LAST:event_pedidosEntregadosBTActionPerformed

    private void eliminarListaProveedoresBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarListaProveedoresBTActionPerformed
       int selectedRow = jTable1.getSelectedRow();

        // Verificar que se haya seleccionado alguna fila
        if (selectedRow != -1) {
            
            
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de borrar el proveedor?\nEsta operación será irreversible",
            "Confirmación", JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.YES_OPTION) {
          proveedores.remove(selectedRow);
          
            JOptionPane.showMessageDialog(null, "Cliente eliminado con Éxito.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
        
            
            
        }else {
     JOptionPane.showMessageDialog(null, "Operación cancelada.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
    }
        
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione el proveedor a eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_eliminarListaProveedoresBTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int selectedRow = jTable6.getSelectedRow();

        // Verificar que se haya seleccionado alguna fila
        if (selectedRow != -1) {
            
            
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de borrar este item?\nEsta operación será irreversible",
            "Confirmación", JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.YES_OPTION) {
          carrito.remove(selectedRow);
          
            JOptionPane.showMessageDialog(null, "Producto eliminado con Éxito.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
        
            
            
        }else {
     JOptionPane.showMessageDialog(null, "Operación cancelada.", "Confirmación"
                        , JOptionPane.INFORMATION_MESSAGE);
    }
        
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione el proveedor a eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
         dtm9.setRowCount(0);
        for (Producto carr : carrito) {
             
        dtm9.addRow(new Object[]{carr.getNombre(), carr.getStock(), carr.getPrecio(),carr.getPrecio()*carr.getStock()});
        ((DefaultTableModel) jTable6.getModel()).fireTableDataChanged();
    }
         dtm9.addRow(new Object[]{"","","Total:",p.getPrecio()});
        ((DefaultTableModel) jTable6.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Proveedores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBT;
    private javax.swing.JButton añadirProductoProvBT;
    private javax.swing.JButton cancelarBT;
    private javax.swing.JTextField cantidadTF;
    private javax.swing.JButton eliminarListaProveedoresBT;
    private javax.swing.JButton estadoPedidoBT;
    private javax.swing.JPanel estadoPedidoJP;
    private javax.swing.JButton hacerPedidoBT;
    private javax.swing.JPanel hacerPedidoJP;
    private javax.swing.JLabel ingresarHaber12;
    private javax.swing.JLabel ingresarHaber13;
    private javax.swing.JLabel ingresarHaber14;
    private javax.swing.JLabel ingresarHaber15;
    private javax.swing.JLabel ingresarHaber16;
    private javax.swing.JLabel ingresarHaber17;
    private javax.swing.JLabel ingresarHaber18;
    private javax.swing.JLabel ingresarHaber19;
    private javax.swing.JLabel ingresarHaber20;
    private javax.swing.JLabel ingresarHaber21;
    private javax.swing.JLabel ingresarHaber22;
    private javax.swing.JLabel ingresarHaber24;
    private javax.swing.JLabel ingresarHaber25;
    private javax.swing.JLabel ingresarHaber26;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField nomProdTF;
    private javax.swing.JTextField nombreEmpresaTF;
    private javax.swing.JToggleButton pedidosEntregadosBT;
    private javax.swing.JTextField precioTF;
    private javax.swing.JTextField precioVTF;
    private javax.swing.JButton proveedoresBT;
    private javax.swing.JButton proveedoresBT1;
    private javax.swing.JPanel proveedoresJP;
    private javax.swing.JButton regresarBT;
    private javax.swing.JTextField rucTF;
    private javax.swing.JButton seleccionarBT;
    private javax.swing.JTextField telefTF;
    // End of variables declaration//GEN-END:variables
}
